# --- SonarCloud Configuration ---
# Documentation: https://docs.sonarsource.com/sonarcloud/advanced-setup/analysis-parameters/

sonar.organization=vincentbattez-github
sonar.projectKey=vincentbattez_gift_grimoire

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/*.test.ts,src/**/*.test.tsx
sonar.exclusions=src/**/*.test.ts,src/**/*.test.tsx,src/**/*.d.ts,src/main.tsx

sonar.typescript.lcov.reportPaths=coverage/lcov.info

sonar.javascript.lcov.reportPaths=coverage/lcov.info
